project:
  type: website

website:
  title: "Hafsa Altaf: Data Insights & Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Hafsa0005
format:
  html:
    theme: cosmo
    css: styles.css



